### ISSUE TITLE
GetPlayersRequest always return an empty list

### ISSUE THREAD

**Issue by Braendstrup** [BytexDigital/BytexDigital.BattlEye.Rcon#5] opened 2020-06-26 18:06 UTC

**Comment by RednecksRevenge** [comment] 2020-08-20 22:30
can confirm

**Comment by RyanTT** [comment] 2020-09-02 02:43
Hi,

I am unable to recreate this issue, are you running the command like this?

```csharp
            bool requestSuccess = networkClient.Fetch(
                command: new GetPlayersRequest(),
                timeout: 5000,
                result: out List<Player> onlinePlayers);```

**Comment by NeutraleNull** [comment] 2020-09-11 22:20
yes and i can also confirm the problem

**Comment by NeutraleNull** [comment] 2020-09-11 22:31
I tracked the problem down to the regex expression in https://github.com/BytexDigital/BytexDigital.BattlEye.Rcon/blob/e78efb7a6ae03074181634037c9252e181ec3561/BytexDigital.BattlEye.Rcon/Commands/GetPlayersRequest.cs#L26
Trying to figure out what exactly is leading to no matches found.

**Comment by RednecksRevenge** [comment] 2020-09-11 22:47
`(\d+) *(\d*\.\d*\.\d*\.\d*):(\d*) *(\d+) *(\S{32})\((\S+)\) (?:(.+) (\(Lobby\))|(.+))`
In the regex you are currently using you are only checking the first digits of the ip from 1 to unlimited and the other ones from 0-9.
With this one you check all digits from 0-unlimited.

**Comment by RyanTT** [comment] 2020-09-15 08:05
Applied a fix based on #6 which I merged from dev into master as version https://www.nuget.org/packages/BytexDigital.BattlEye.Rcon/1.0.3-beta.1 with #7 . Please provide feedback whether this fixed your issue entirely.

**Comment by NeutraleNull** [comment] 2020-09-16 15:07
The is in lobby detection is not working as intended. It always returns true.

**Comment by RyanTT** [comment] 2020-09-17 13:59
Addressed the issue, please try version https://www.nuget.org/packages/BytexDigital.BattlEye.Rcon/1.0.3-beta.2

**Comment by NeutraleNull** [comment] 2020-09-17 17:03
Works for me so far.

**Comment by Braendstrup** [comment] 2020-09-22 07:58
I can confirm, it seems to work now

**Closed as completed** 2021-01-29 14:22 UTC
